[package]
name = "random-picker"
version = "0.0.0"
authors = ["you"]
edition = "2021"
publish = false

[lib]
path = "src/random_picker.rs"

[dependencies.multiversx-sc]
version = "0.51.1"

[dev-dependencies]
num-bigint = "0.4"

[dev-dependencies.multiversx-sc-scenario]
version = "0.51.1"

[workspace]
members = [
    ".",
    "meta",
]
