// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            9
// Async Callback:                       1
// Total number of exported functions:  12

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    lottery
    (
        init => init
        upgrade => upgrade
        getRandomPickerAddress => random_picker_address
        getLottery => lottery
        getLotteriesId => lotteries_id
        getLastLotteryId => last_lottery_id
        getLotteryStatus => get_lottery_status
        getTickets => tickets
        createLottery => create_lottery
        buyTickets => buy_tickets
        callRewards => call_rewards
    )
}

multiversx_sc_wasm_adapter::async_callback! { lottery }
